### ISSUE TITLE
Don't define constants just to make code work right

### ISSUE THREAD

**Issue by mayisa87** [asharif123/slot_machine#1]
https://github.com/asharif123/slot_machine/blob/0ef0ec3e33a22886ddb97b0c441837cd0f7a1073/Program.cs#L40-L41

I really like that you use constants from beginning on! Great work!
If you use constants, you should not define constants "to make your code work". What does it mean?

Like your "ENDING_ROW", it has the value 2, as you want the loop to loop from 0 to 2. You choose 2 because you know, that the grid has 3 rows, so you want to loop to length-1  which is 2. 

So in general it works to have a constant with value 2. But better would be to define a constant
ROW_COUNT = 3 and in the loop you use <ROW_COUNT or <=ROW_COUNT-1

So better define 2 constants ROW_COUNT, COLUMN_COUNT. So if you want to later on change the size of your grid, you can just change those 2 constants and it is clear to everyone what's going on.

Same with your STARTING_ROW with value 0. It is not necessary to define constants for the value 0. Every developer knows what it means if a loop starts at 0, so this is a special case, where it is ok to just write 0 :)

**Comment by asharif123** [comment]
fixed issue #1 by getting rid of unnecessary constants
