### ISSUE TITLE
Declaration of variables

### ISSUE THREAD

**Issue by mayisa87** [asharif123/slot_machine#12]
https://github.com/asharif123/slot_machine/blob/e55a9554e7e7c2779e7de5cbf3fc178b0af71346/Program.cs#L74

The Random generator object is a special case in code, you should only have one that is used in the whole application when generating random numbers.
So the best choice is, to move the declaration of the Random generator variable outside of the Main method.

You will soon learn more about fields and other stuff. But for now you can do it like this:

```
public static readonly Random rng = new Random();

public static void Main(string args[])
```

https://github.com/asharif123/slot_machine/blob/e55a9554e7e7c2779e7de5cbf3fc178b0af71346/Program.cs#L73

The slot machine grid, here it would be enought to define the array itself only once at the beginning of your Main method (after defining your constants), as the values are currently always overriden, it is enough to create it once at the beginning.

**Comment by asharif123** [comment]
fixed issue #12 by reorienting declaration of variables for random rng and slot machine
