### ISSUE TITLE
Diagonal 2 check not yet right

### ISSUE THREAD

**Issue by mayisa87** [asharif123/slot_machine#13]
https://github.com/asharif123/slot_machine/blob/e55a9554e7e7c2779e7de5cbf3fc178b0af71346/Program.cs#L200

The implementation look fine, so it works. Just one thing about naming and your lengthOfArray variable. It confused me first. 

What about to name it "colPosition" and initialize it with length-1 first, so like:
`int colIndex= spinningSlotMachine.GetLength(0)-1;`

and in code you do:
`if (spinningSlotMachine[rowIndex, colIndex] == spinningSlotMachine[rowIndex + 1, colIndex-1])`

So it is clear to someone seeing your code for the first time, that you declare here the colIndexto be used and in the if it is much easier to follow your calculations. What do you think?

**Comment by asharif123** [comment]
fixed issue #13 by redefining variable names for diagonal testcase when matching values from top left to bottom right
