### ISSUE TITLE
Missed using constant in your if

### ISSUE THREAD

**Issue by mayisa87** [asharif123/slot_machine#14]
https://github.com/asharif123/slot_machine/blob/e55a9554e7e7c2779e7de5cbf3fc178b0af71346/Program.cs#L20
https://github.com/asharif123/slot_machine/blob/e55a9554e7e7c2779e7de5cbf3fc178b0af71346/Program.cs#L229

Use the constant in your if too.

**Comment by asharif123** [comment]
fixed issue #14 by using constant for optionToContinue input
