### ISSUE TITLE
Don't use static variables

### ISSUE THREAD

**Issue by incredibleLeitman** [asharif123/slot_machine#16]
https://github.com/asharif123/slot_machine/blob/5cace415dc798f930b8680053a6eed5f24918381/UIMethods.cs#L36-L37
unless they are constants!

Getting used to this will make it very hard vor you understanding classes later on.

If you need specific variables on multiple places in your code you need to handle them using input parameters and return values from functions like:
```cs
int value = UIMethods.GetSomeValue();
bool result = LogicMethods.DoSomethingWithValue(value);
UIMethods.PrintResult(result);
```

**Comment by asharif123** [comment]
fixed issue #16 by getting rid of static variables
