### ISSUE TITLE
prefer "return" over "Environment.Exit"

### ISSUE THREAD

**Issue by incredibleLeitman** [asharif123/slot_machine#17]
https://github.com/asharif123/slot_machine/blob/5cace415dc798f930b8680053a6eed5f24918381/Program.cs#L23
https://github.com/asharif123/slot_machine/blob/5cace415dc798f930b8680053a6eed5f24918381/Program.cs#L33

When calling "return" from within the Program.Main this will also end your program, having the same effect as "Environment.Exit" but you have an easier time when extracting code into functions. Using return allows you to put additional code *after* you want your program to exit like cleanup or closing resources

**Comment by asharif123** [comment]
fixed issue #17 by replacing environment.exit(0) with return
