### ISSUE TITLE
Do you need a random object here?

### ISSUE THREAD

**Issue by incredibleLeitman** [asharif123/slot_machine#18]
https://github.com/asharif123/slot_machine/blob/5cace415dc798f930b8680053a6eed5f24918381/Program.cs#L7

If no, you can remove it, 
and also make sure other modules/files can access it and don't create an additional instance (like in Logic.spinningSlotMachine or UIMethods)

**Comment by asharif123** [comment]
got rid of issue 18 by getting rid of random
