### ISSUE TITLE
Naming: functions start with a verb that indicates what they are doing and an uppercase letter

### ISSUE THREAD

**Issue by incredibleLeitman** [asharif123/slot_machine#19]
https://github.com/asharif123/slot_machine/blob/7d8724c485ee0c800f13a8a9a8410f7f2ed19380/Logic.cs#L14
https://github.com/asharif123/slot_machine/blob/7d8724c485ee0c800f13a8a9a8410f7f2ed19380/Logic.cs#L37
...

https://github.com/asharif123/slot_machine/blob/7d8724c485ee0c800f13a8a9a8410f7f2ed19380/UIMethods.cs#L21
https://github.com/asharif123/slot_machine/blob/7d8724c485ee0c800f13a8a9a8410f7f2ed19380/UIMethods.cs#L28
...

**Comment by asharif123** [comment]
fixed issue #19 by fixing naming of functions
