### ISSUE TITLE
Why this method?

### ISSUE THREAD

**Issue by mayisa87** [asharif123/slot_machine#2]
https://github.com/asharif123/slot_machine/blob/0ef0ec3e33a22886ddb97b0c441837cd0f7a1073/Program.cs#L32

As you are having your whole logic in this SlotMachine method, you could just move it to your Main method too.
With next step and exercise we will work with methods anyway. So now better stick to writting everything in your Main method!

**Comment by asharif123** [comment]
fixed issue #2 by getting rid of unnecessary methods
