### ISSUE TITLE
You should not use System.Exit

### ISSUE THREAD

**Issue by incredibleLeitman** [asharif123/slot_machine#20]
https://github.com/asharif123/slot_machine/blob/7d8724c485ee0c800f13a8a9a8410f7f2ed19380/Program.cs#L31

because this instantly closes your program.

Also return is not that optimal in the program Main:
https://github.com/asharif123/slot_machine/blob/7d8724c485ee0c800f13a8a9a8410f7f2ed19380/Program.cs#L60-L65

Instead you should in this case use breaks and flags to leave the loops
so that all paths reach the same common ending.

```
program.cs Main

while (val)
{
  // do some things
  
  // if you here use return your program just exits, never reaching END_BLOCK
  // return;
  // or System.Exit(x);
  
  // so you better want to either use a break
  break;
  
  // or let the loop exit when the while-condition is not valid anymore
}
  
// END_BLOCK  
// this is the point where all paths should end
UIMethods.PrintExit(); // thanks for playing

// because you can do cleanups, logging, etc...
```

**Comment by asharif123** [comment]
fixed issue #20 by getting rid of environmental exit
