### ISSUE TITLE
Do not create a new Random object in a function

### ISSUE THREAD

**Issue by incredibleLeitman** [asharif123/slot_machine#21]
https://github.com/asharif123/slot_machine/blob/7d8724c485ee0c800f13a8a9a8410f7f2ed19380/Logic.cs#L14-L21
because this can lead to strange behavior and the same random values

Instead you should have one instance that is public accessible somewhere in your code or pass it per param

**Comment by asharif123** [comment]
fixed issue #21 by declaring random as a public variable
