### ISSUE TITLE
There should be no Console.X calls in your code unless in the UI class

### ISSUE THREAD

**Issue by incredibleLeitman** [asharif123/slot_machine#22]
https://github.com/asharif123/slot_machine/blob/7d8724c485ee0c800f13a8a9a8410f7f2ed19380/Logic.cs#L30
https://github.com/asharif123/slot_machine/blob/7d8724c485ee0c800f13a8a9a8410f7f2ed19380/Logic.cs#L67
https://github.com/asharif123/slot_machine/blob/7d8724c485ee0c800f13a8a9a8410f7f2ed19380/Logic.cs#L75
...

This applies for Read and WriteLine

Instead you need to split functionality in the UI and logic part

**Comment by asharif123** [comment]
fixed issue #21 by getting rid of console statements in logic.cs file
