### ISSUE TITLE
You should not call any UI methods from within your logic code

### ISSUE THREAD

**Issue by incredibleLeitman** [asharif123/slot_machine#24]
https://github.com/asharif123/slot_machine/blob/b03724f365e0d607ecf640b57eadbb0dcb5addaf/Logic.cs#L31-L32

https://github.com/asharif123/slot_machine/blob/b03724f365e0d607ecf640b57eadbb0dcb5addaf/Logic.cs#L65-L74

The idea behind the ui / logic split is, that your logic module should be able to run without any console input.
This becomes very important when you later want to implement unit tests where you call functions of your code and verify the behavior: this will not work if you expect the existence of a console. 
The same applies when you would like to build a UI around your program -> in this case you cannot just use a Console.WriteLine when displaying for example the slot machine grid

**Comment by asharif123** [comment]
fixed issue #24 by removing UIMethods from logic.cs file
