### ISSUE TITLE
Duplicate code on inputing wagerValue

### ISSUE THREAD

**Issue by AlexKap23** [asharif123/slot_machine#26]
https://github.com/asharif123/slot_machine/blob/016b26241c535a0178f3aa7e74b3ca2cc2933833/UIMethods.cs#L73-L94

Since you are using a loop for validating your input you don't have to get the input unvalidated outside the loop and then check for it again. 
You can start reading inputs until you find something valid and all of this inside the while loop.

**Comment by asharif123** [comment]
fixed issue #26 by getting rid of duplicate code in InputWagerAmount method
