### ISSUE TITLE
Use TryParse

### ISSUE THREAD

**Issue by AlexKap23** [asharif123/slot_machine#27]
https://github.com/asharif123/slot_machine/blob/016b26241c535a0178f3aa7e74b3ca2cc2933833/UIMethods.cs#L86-L87

U can make use of TryParse to get a validated integer input from the console, instead of getting a string and converting it.

https://learn.microsoft.com/en-us/dotnet/api/system.int32.tryparse?view=net-8.0

**Comment by asharif123** [comment]
fixed issue #27 by using tryParse to convert str to int
