### ISSUE TITLE
This method is not only Printing

### ISSUE THREAD

**Issue by AlexKap23** [asharif123/slot_machine#28]
https://github.com/asharif123/slot_machine/blob/016b26241c535a0178f3aa7e74b3ca2cc2933833/UIMethods.cs#L100-L120

Method's name is PrintMatchingOption but it's not only printing the available options, it's also getting the user's input. This method should be renamed to something else.

Also issue #26 should be revisited for this us the same mechanism applies to this for getting a valid input

**Comment by asharif123** [comment]
fixed issue #28 by changing method name from PrintMatchingOption to InputMatchingOption
