### ISSUE TITLE
Add your availabe options to a list or build a condition with &&

### ISSUE THREAD

**Issue by AlexKap23** [asharif123/slot_machine#30]
https://github.com/asharif123/slot_machine/blob/016b26241c535a0178f3aa7e74b3ca2cc2933833/UIMethods.cs#L109

The solution you followed is ok but it's not generic, as it will work only for this case. Putting everyting on a List will do the same and work for strings, chars, numbers, or even objects.

The "dummy" solution would be to check in an if case as you previously did but change OR to AND as in order for an input to be invalid it shouldn't be h, and it shouldn't be v and it shouldn't be d all at the same time

**Comment by asharif123** [comment]
fixed issue #30 by using list to store matching options

**Comment by AlexKap23** [comment]
List<char> LINE_MATCHING_OPTIONS = new List<char> { 'h', 'v', 'd'};

Why don't U use your already defined constants? (HORIZONTAL_OPTION, VERTICAL_OPTION,DIAGONAL_OPTION)
