### ISSUE TITLE
Extract a method out of this

### ISSUE THREAD

**Issue by AlexKap23** [asharif123/slot_machine#31]
https://github.com/asharif123/slot_machine/blob/de21734977c8c18821eec96e5153c7e616c860d3/Program.cs#L61-L109

Code for Horizontal, Vertical and Diagonal is almost the same. You can create a method and invoke it with different parameter values for each option.

**Comment by asharif123** [comment]
fixed issue #31 by using AmountMoneyLeft method in UIMethods.cs file
