### ISSUE TITLE
don't refer to Main

### ISSUE THREAD

**Issue by incredibleLeitman** [asharif123/slot_machine#4]
https://github.com/asharif123/slot_machine/blob/14315b7a80e1f630ce23fd669a679d1b5e753fd2/Program.cs#L23-L27
This may not do what you expect ☝️ 
In this case you first re-call the previously executed code, then the rest of the current main
but after this follows the rest of the originally called main method.

Its better to move this code within a loop if you want to execute it multiple times

**Comment by mayisa87** [comment]
So what you currently do is, that in case of an invalid input, you call again the Main() method. 

But do you know what exactly will happen, if you do so? You are doing an recursive call, which you should avoid.


![image](https://github.com/asharif123/slot_machine/assets/130921606/1dcb1bc0-6c6e-4ef4-9cee-5d58ef23fe63)
You first end up in the if-statement with the invalid input (1), where you again call the Main() method, which makes you start over at the beginning again (2). User maybe enters now an valid input (3) and you go through allof your code 
But... then after finishing the main method call you did (at 1), the code will continue after the call. This is step (4). 

You see, it is getting complicated here! So what you should do? If you want the user to enter a valid value, use a while loop, that is looping as long until the user entered a valid input.

while(notValidInpu)
{
   wager = Console.ReadLine();
   //check if wager is a valid one
   if valid, stop loop
}
