### ISSUE TITLE
Better naming, and usage of constants

### ISSUE THREAD

**Issue by mayisa87** [asharif123/slot_machine#6]
https://github.com/asharif123/slot_machine/blob/268aea891939e88901a410dd0e3a41a84e75411d/Program.cs#L50

Please choose a better name for your variable "val", like "lineType" , always call it what it is.

And define constants also for your characters user can enter. So like your 'h','v','d' or if you got somewhere an 'y' or 'n' to enter, those user inputs should be defined as constants too. Can be done the same as your integer constants, but only of type char.

**Comment by asharif123** [comment]
fixed issue #6 by providing better naming for variables and declaring constants
