### ISSUE TITLE
No hardcoded checks, be generic in your implementation

### ISSUE THREAD

**Issue by mayisa87** [asharif123/slot_machine#7]
https://github.com/asharif123/slot_machine/blob/268aea891939e88901a410dd0e3a41a84e75411d/Program.cs#L85-L87

As already mentioned in WhatsApp Chat, don't do hardcoded implementations. In case of this 3x3 grid, it seems easy to just check all values in an if-statement against each other, but this is not the goal of the exercise at all.

When filling the array, you already used a nested loop to do so. Think about, how you could walk through your array with loops and within your loop check the values against each other. 

You should therefore maybe rewatch this video: https://course.raketementoring.com/courses/rakete-mentoring/lectures/50269871

Best would be to do some drawing and think about, if you are using a nested loop and the indexes/variables of these loops, how you can compare the values then.

**Comment by asharif123** [comment]
fixed issue #7 by getting rid of hard coded if checks
